### ISSUE TITLE
[Bug] - Able to access User Dashboard and Events without logging in

### ISSUE THREAD

**Issue by TekuriSaiAkhil** [gcivil-nyu-org/wed-fall24-team3#132]
**Description:**
Able to access User Dashboard and Events without login. 

**Steps to Reproduce:**
Access these URLs without logging in

http://eventsphere-env2.eba-garccznv.us-west-2.elasticbeanstalk.com/events/userhome/
<img width="1435" alt="image" src="https://github.com/user-attachments/assets/148e4f20-102c-4d06-be6f-1f1b90fe0830">

http://eventsphere-env2.eba-garccznv.us-west-2.elasticbeanstalk.com/events/userevents/
<img width="1435" alt="image" src="https://github.com/user-attachments/assets/fedf7f3e-195b-4140-b266-2ae3fac8ff50">

**Expected Behavior:**
Redirect to login/signup page

**Comment by aakashshankar** [comment]
I don't think this is a bug. See the Login and Signup options in the navbar. I tried this too and it asks me to log in when want to buy a ticket, which is expected.

![Screenshot 2024-11-14 at 1 30 27 PM](https://github.com/user-attachments/assets/faa2cb29-9631-4267-9b0c-85d758e04598)

**Comment by aakashshankar** [comment]
> So, you mean you allow users to view events, etc without login?

yes, looks like it. makes sense too

> If this is the case having a profile button in /events/userhome/ doesn't make sense if the user is not logged in!!

Agree that it's a bit counter intuitive, but that still doesn't make it a bug. Click on the `Profile` button and you'll be directed to login. Maybe an enhancement/suggestion that replaces that button with a login.

> Also, In the testing party doc, It is nowhere mentioned that a user without login can view events, etc.

I'm not even in their team lol, that's upto the team.

**Comment by simarmehta** [comment]
Thanks for clearing it up @aakashshankar , yes you are correct that that is on purpose that even thought the user hasn't logged in, user can see listed events, but @TekuriSaiAkhil you are correct to point out that there shouldn't be a profile button then, will work on this!

Additionally sorry if this was not mentioned explicitly in the document!
