### ISSUE TITLE
[Bug] Able to enter invalid emails and phone number in the but ticket form fields and Submit

### ISSUE THREAD

**Issue by TekuriSaiAkhil** [gcivil-nyu-org/wed-fall24-team3#133]
**Description:**
Able to enter invalid emails and phone numbers in the but tickets form fields and Submit.
No error message is shown before and after submit.

**Steps to Reproduce:**
After login, go to any event, go to buy tickets.
Enter invalid emails and phone numbers in the but tickets form fields as shown below and submit.
Click on But tickets. (Able to submit the invalid form)

<img width="1435" alt="image" src="https://github.com/user-attachments/assets/30eef783-5325-4dd0-a9dc-f18c11fff4ac">

**Expected Behavior:**
Should not allow users to submit the form if the fields are invalid.
Display some error messages.

**Comment by simarmehta** [comment]
Already reported by someone beforehand, and as I said will display a warning message!
