### ISSUE TITLE
[Bug] Able to access login url and signup url even after logging in

### ISSUE THREAD

**Issue by TekuriSaiAkhil** [gcivil-nyu-org/wed-fall24-team3#134]
Description:
Able to access login url even after logging in.

Steps to Reproduce:
1. log in as a user -> after login -> goes to user dashboard
2. Access login page: http://eventsphere-env2.eba-garccznv.us-west-2.elasticbeanstalk.com/events/login/ 
3. Access signup page: http://eventsphere-env2.eba-garccznv.us-west-2.elasticbeanstalk.com/events/signup/
4. login/signup again!!

Expected Behavior:
Shouldn't allow access to login page/register page or "/" path after user login.
Ideally, users should be redirected to the respective dashboards if they hit the login/register urls

**Comment by simarmehta** [comment]
Yes this shouldn't be allowed it should redirect to home page
