### ISSUE TITLE
Testing party bug: Updating my profile doesn't seem to do anything

### ISSUE THREAD

**Issue by ahhcash** [gcivil-nyu-org/wed-fall24-team3#135]
## Description
I created a new account and decided to update my profile, i.e, fill in my first and last names, age, bio, location and interests. But updating this info does nothing.

## Steps to reproduce
1. Create an account
2. Select `Profile` from the navbar
3. Add your info
4. Click on `Update profile`

Nothing happens. When click on profile again, the info isn't reflected. If I choose `Account Info`, everything is reset to blank fields

## Screenshots

https://github.com/user-attachments/assets/43ec7bb3-4839-4038-a4b2-e7ea5e7a77bb

## Expected behavior
The profile update should be reflected. I should be able to see it when I view my profile.

**Comment by simarmehta** [comment]
@aakashshankar , looking at the video this happens because of incorrect email format entered, it should work if you enter a correct format although, there should be an error message here to say incorrect format, rather than what currently happens, Will investigate it further and resolve!
