### ISSUE TITLE
Testing party bug - The app is showing my previous event created notifications on login page

### ISSUE THREAD

**Issue by shub-garg** [gcivil-nyu-org/wed-fall24-team3#137]
![image](https://github.com/user-attachments/assets/e6e022bb-6135-4b5f-a8c8-2b894d3094ae)

Steps to reproduce:
1. Create 3 events using the creator dashboard
2. Logout and navigate back to the sign in page
3. You will see the notifcations

**Comment by simarmehta** [comment]
@shub-garg mentioned this in the doc , this error  persists, please go through that
