### ISSUE TITLE
Testing party bug - Unable to buy tickets, nothing happens after clicking Buy Tickets, past events appear purchasable

### ISSUE THREAD

**Issue by soniasusanto** [gcivil-nyu-org/wed-fall24-team3#141]
- Go to Lunch at NYU Manhattan, notice you cannot buy any tickets

https://github.com/user-attachments/assets/83ead349-199c-43d4-bbbe-70cde8bbf7a9

- Click on Events and then go to the same event, Lunch at NYU Manhattan
- See a long list of red notifications which disappears after a while
![Screenshot 2024-11-16 at 4 31 56 PM](https://github.com/user-attachments/assets/b37e5094-4378-43c6-b0ba-ebe5c8541bde)

Notice the event is also in the past but still purchasable
![Screenshot 2024-11-16 at 4 37 21 PM](https://github.com/user-attachments/assets/5b1217fd-ad82-48aa-b982-82019613f1fc)

Expected behavior:

- There should be immediate feedback to the user upon clicking 'Buy Tickets' to let the user know if the purchase was successful or not. There should not be a list of red notifications on the event page when the user navigates to the event page again
- Events in the past should not be displayed as purchasable events

**Comment by simarmehta** [comment]
Explicitly mentioned inn the document that there is this issue when number of tickets are exhausted, please take a look at the testing document.

Additionally second issue looks like a mistake old events even though listed should no longer be purchasable, will fix this @soniasusanto  !

**Comment by soniasusanto** [comment]
@simarmehta , I think when I was testing, I didn't know that number of tickets were exhausted, maybe it might be good to show the user that there are no more tickets available
